// (* keep_hierarchy = "yes" *)
module inst_mem (
    input  wire [31:0] pc_address,
    output reg  [31:0] instruction
);
  localparam NUM_OF_INST = 200;
  localparam ADDR_W = $clog2(NUM_OF_INST);

  // Force distributed ROM (combinational read)
  (* rom_style = "distributed" *) reg [31:0] memory [0:NUM_OF_INST-1];
  wire [ADDR_W-1:0] word_addr = pc_address[2 + ADDR_W - 1 : 2];

  integer i;
  initial begin
    // default fill with NOP
    for (i = 0; i < NUM_OF_INST; i = i + 1) begin
      memory[i] = 32'h00000013;
    end

    // paste your instructions here (generated by python)
    memory[0] = 32'h0000a437;
    memory[1] = 32'h000084b7;
    memory[2] = 32'h00002937;
    memory[3] = 32'h40000b93;
    memory[4] = 32'h00000d13;
    memory[5] = 32'h0084a283;
    memory[6] = 32'h0012f293;
    memory[7] = 32'hfe028ce3;
    memory[8] = 32'h00000293;
    memory[9] = 32'h00540333;
    memory[10] = 32'h00030023;
    memory[11] = 32'h00128293;
    memory[12] = 32'h08000393;
    memory[13] = 32'hfe72c8e3;
    memory[14] = 32'h00100993;
    memory[15] = 32'h04000a13;
    memory[16] = 32'h00000a93;
    memory[17] = 32'h00100b13;
    memory[18] = 32'h01492023;
    memory[19] = 32'h014402b3;
    memory[20] = 32'h0ff00313;
    memory[21] = 32'h00628023;
    memory[22] = 32'h0044a283;
    memory[23] = 32'h07f2f293;
    memory[24] = 32'h00540333;
    memory[25] = 32'h00034383;
    memory[26] = 32'hfe0398e3;
    memory[27] = 32'h0aa00393;
    memory[28] = 32'h00730023;
    memory[29] = 32'h0084a283;
    memory[30] = 32'h0012f293;
    memory[31] = 32'hf8028ce3;
    memory[32] = 32'h0004a283;
    memory[33] = 32'h0082f313;
    memory[34] = 32'h00030463;
    memory[35] = 32'h00100993;
    memory[36] = 32'h0042f313;
    memory[37] = 32'h00030463;
    memory[38] = 32'hfff00993;
    memory[39] = 32'h0022f313;
    memory[40] = 32'h00030463;
    memory[41] = 32'h01000993;
    memory[42] = 32'h0012f313;
    memory[43] = 32'h00030463;
    memory[44] = 32'hff000993;
    memory[45] = 32'h0044a283;
    memory[46] = 32'h41a28333;
    memory[47] = 32'hfb734ce3;
    memory[48] = 32'h00028d13;
    memory[49] = 32'h013a02b3;
    memory[50] = 32'h07f2f293;
    memory[51] = 32'h00540333;
    memory[52] = 32'h00034383;
    memory[53] = 32'h0aa00e13;
    memory[54] = 32'h05c38c63;
    memory[55] = 32'h002a9313;
    memory[56] = 32'h00690333;
    memory[57] = 32'h00032383;
    memory[58] = 32'h00740e33;
    memory[59] = 32'h000e0023;
    memory[60] = 32'h001a8a93;
    memory[61] = 32'h10000e93;
    memory[62] = 32'h01dac463;
    memory[63] = 32'h00000a93;
    memory[64] = 32'h002b1313;
    memory[65] = 32'h00690333;
    memory[66] = 32'h00532023;
    memory[67] = 32'h001b0b13;
    memory[68] = 32'h10000e93;
    memory[69] = 32'h01db4463;
    memory[70] = 32'h00000b13;
    memory[71] = 32'h00540333;
    memory[72] = 32'h0ff00393;
    memory[73] = 32'h00730023;
    memory[74] = 32'h00028a13;
    memory[75] = 32'hf49ff06f;
    memory[76] = 32'hfd1ff06f;
    memory[77] = 32'hf25ff06f;
  end

  always @(*) begin
    instruction = memory[word_addr];
  end
endmodule
