// (* keep_hierarchy = "yes" *)
module inst_mem (
    input  wire [31:0] pc_address,
    output reg  [31:0] instruction
);
  localparam NUM_OF_INST = 1024;
  localparam ADDR_W = $clog2(NUM_OF_INST);

  // Force distributed ROM (combinational read)
  (* rom_style = "distributed" *) reg [31:0] memory [0:NUM_OF_INST-1];
  wire [ADDR_W-1:0] word_addr = pc_address[2 + ADDR_W - 1 : 2];

  integer i;
  initial begin
    // default fill with NOP
    for (i = 0; i < NUM_OF_INST; i = i + 1) begin
      memory[i] = 32'h00000013;
    end

    // paste your instructions here (generated by python)
    memory[0] = 32'h00008437;
    memory[1] = 32'h000094b7;
    memory[2] = 32'h0000a937;
    memory[3] = 32'h000019b7;
    memory[4] = 32'h0000ba37;
    memory[5] = 32'h00800a93;
    memory[6] = 32'h00600b13;
    memory[7] = 32'h00000c13;
    memory[8] = 32'h001c0c13;
    memory[9] = 32'h00042303;
    memory[10] = 32'h00000293;
    memory[11] = 32'h00000293;
    memory[12] = 32'h00000393;
    memory[13] = 32'h007c7293;
    memory[14] = 32'h1a029263;
    memory[15] = 32'h00000c93;
    memory[16] = 32'h01800e13;
    memory[17] = 32'h01cace63;
    memory[18] = 32'h01c00e93;
    memory[19] = 32'h01dada63;
    memory[20] = 32'h00500f13;
    memory[21] = 32'h01eb4663;
    memory[22] = 32'h00100c93;
    memory[23] = 32'h0500006f;
    memory[24] = 32'h03400e13;
    memory[25] = 32'h03cac263;
    memory[26] = 32'h03800e93;
    memory[27] = 32'h01dade63;
    memory[28] = 32'h00300f13;
    memory[29] = 32'h01eb4a63;
    memory[30] = 32'h00600f13;
    memory[31] = 32'h01eb5663;
    memory[32] = 32'h00100c93;
    memory[33] = 32'h0280006f;
    memory[34] = 32'h05800e13;
    memory[35] = 32'h03cac063;
    memory[36] = 32'h05c00e93;
    memory[37] = 32'h01dadc63;
    memory[38] = 32'h00100f13;
    memory[39] = 32'h01eb4863;
    memory[40] = 32'h00400f13;
    memory[41] = 32'h01eb5463;
    memory[42] = 32'h00100c93;
    memory[43] = 32'h00137e13;
    memory[44] = 32'h000e0c63;
    memory[45] = 32'h000c8a63;
    memory[46] = 32'h000b0863;
    memory[47] = 32'hfffb0b13;
    memory[48] = 32'h00400e93;
    memory[49] = 32'h01d3e3b3;
    memory[50] = 32'h00237e13;
    memory[51] = 32'h000e0e63;
    memory[52] = 32'h000c8c63;
    memory[53] = 32'h00700e93;
    memory[54] = 32'h01db5863;
    memory[55] = 32'h001b0b13;
    memory[56] = 32'h00800e93;
    memory[57] = 32'h01d3e3b3;
    memory[58] = 32'h00437e13;
    memory[59] = 32'h060e0a63;
    memory[60] = 32'h060a8863;
    memory[61] = 32'hfffa8293;
    memory[62] = 32'h00000f93;
    memory[63] = 32'h00200e93;
    memory[64] = 32'h01db4a63;
    memory[65] = 32'h01e00e93;
    memory[66] = 32'h01d2c663;
    memory[67] = 32'h02200e93;
    memory[68] = 32'h03d2ce63;
    memory[69] = 32'h00300e93;
    memory[70] = 32'h01db4a63;
    memory[71] = 32'h03e00e93;
    memory[72] = 32'h01d2c663;
    memory[73] = 32'h04200e93;
    memory[74] = 32'h03d2c263;
    memory[75] = 32'h00100e93;
    memory[76] = 32'h01db4a63;
    memory[77] = 32'h06000e93;
    memory[78] = 32'h01d2c663;
    memory[79] = 32'h06400e93;
    memory[80] = 32'h01d2c663;
    memory[81] = 32'h000f8863;
    memory[82] = 32'h0180006f;
    memory[83] = 32'h00100f93;
    memory[84] = 32'hfddff06f;
    memory[85] = 32'hfffa8a93;
    memory[86] = 32'h00100e93;
    memory[87] = 32'h01d3e3b3;
    memory[88] = 32'h00837e13;
    memory[89] = 32'h060e0c63;
    memory[90] = 32'h07c00e93;
    memory[91] = 32'h07dad863;
    memory[92] = 32'h001a8293;
    memory[93] = 32'h00000f93;
    memory[94] = 32'h00200e93;
    memory[95] = 32'h01db4a63;
    memory[96] = 32'h01e00e93;
    memory[97] = 32'h01d2c663;
    memory[98] = 32'h02200e93;
    memory[99] = 32'h03d2ce63;
    memory[100] = 32'h00300e93;
    memory[101] = 32'h01db4a63;
    memory[102] = 32'h03e00e93;
    memory[103] = 32'h01d2c663;
    memory[104] = 32'h04200e93;
    memory[105] = 32'h03d2c263;
    memory[106] = 32'h00100e93;
    memory[107] = 32'h01db4a63;
    memory[108] = 32'h06000e93;
    memory[109] = 32'h01d2c663;
    memory[110] = 32'h06400e93;
    memory[111] = 32'h01d2c663;
    memory[112] = 32'h000f8863;
    memory[113] = 32'h0180006f;
    memory[114] = 32'h00100f93;
    memory[115] = 32'hfddff06f;
    memory[116] = 32'h001a8a93;
    memory[117] = 32'h00200e93;
    memory[118] = 32'h01d3e3b3;
    memory[119] = 32'h00f37f93;
    memory[120] = 32'h00439e93;
    memory[121] = 32'h01dfefb3;
    memory[122] = 32'h00faff13;
    memory[123] = 32'h008f1f13;
    memory[124] = 32'h01efefb3;
    memory[125] = 32'h01fa2023;
    memory[126] = 32'h00000293;
    memory[127] = 32'h00598e33;
    memory[128] = 32'h000e4e83;
    memory[129] = 32'h00590f33;
    memory[130] = 32'h01df0023;
    memory[131] = 32'h00128293;
    memory[132] = 32'h40000e13;
    memory[133] = 32'hffc2c4e3;
    memory[134] = 32'h007b1293;
    memory[135] = 32'h015282b3;
    memory[136] = 32'h012282b3;
    memory[137] = 32'hfff00e13;
    memory[138] = 32'h01c28023;
    memory[139] = 32'h01c280a3;
    memory[140] = 32'h01c28123;
    memory[141] = 32'h01c281a3;
    memory[142] = 32'h0004a023;
    memory[143] = 32'hde5ff06f;
  end

  always @(*) begin
    instruction = memory[word_addr];
  end
endmodule
