// (* keep_hierarchy = "yes" *)
module inst_mem (
    input  wire [31:0] pc_address,
    output reg  [31:0] instruction
);
  localparam NUM_OF_INST = 200;
  localparam ADDR_W = $clog2(NUM_OF_INST);

  // Force distributed ROM (combinational read)
  (* rom_style = "distributed" *) reg [31:0] memory [0:NUM_OF_INST-1];
  wire [ADDR_W-1:0] word_addr = pc_address[2 + ADDR_W - 1 : 2];

  integer i;
  initial begin
    // default fill with NOP
    for (i = 0; i < NUM_OF_INST; i = i + 1) begin
      memory[i] = 32'h00000013;
    end

    // paste your instructions here (generated by python)
    memory[0] = 32'h01000513;
    memory[1] = 32'h00800593;
    memory[2] = 32'h00000613;
    memory[3] = 32'h00008f37;
    memory[4] = 32'h0000afb7;
    memory[5] = 32'h004f2283;
    memory[6] = 32'h40c28333;
    memory[7] = 32'h01435313;
    memory[8] = 32'hfe030ae3;
    memory[9] = 32'h00028613;
    memory[10] = 32'h000f2383;
    memory[11] = 32'h0083fe13;
    memory[12] = 32'h000e0863;
    memory[13] = 32'hfe250e93;
    memory[14] = 32'h000ed463;
    memory[15] = 32'h00150513;
    memory[16] = 32'h0043fe13;
    memory[17] = 32'h000e0863;
    memory[18] = 32'hfff50e93;
    memory[19] = 32'h000e8463;
    memory[20] = 32'hfff50513;
    memory[21] = 32'h0013fe13;
    memory[22] = 32'h000e0c63;
    memory[23] = 32'hff850e93;
    memory[24] = 32'h000e9863;
    memory[25] = 32'hfff58e93;
    memory[26] = 32'h000e8463;
    memory[27] = 32'hfff58593;
    memory[28] = 32'h0023fe13;
    memory[29] = 32'h000e0863;
    memory[30] = 32'hfe258e93;
    memory[31] = 32'h000ed463;
    memory[32] = 32'h00158593;
    memory[33] = 32'hff850e93;
    memory[34] = 32'h000e8863;
    memory[35] = 32'hfe258e93;
    memory[36] = 32'h000ed463;
    memory[37] = 32'h00158593;
    memory[38] = 32'h00000293;
    memory[39] = 32'h005f8333;
    memory[40] = 32'h00030023;
    memory[41] = 32'h00128293;
    memory[42] = 32'h08000393;
    memory[43] = 32'hfe72c8e3;
    memory[44] = 32'h06000293;
    memory[45] = 32'h005f8333;
    memory[46] = 32'h08000e13;
    memory[47] = 32'h01c30023;
    memory[48] = 32'h00128293;
    memory[49] = 32'h08000393;
    memory[50] = 32'hfe72c6e3;
    memory[51] = 32'h04400293;
    memory[52] = 32'h005f8333;
    memory[53] = 32'h08000e13;
    memory[54] = 32'h01c30023;
    memory[55] = 32'h00128293;
    memory[56] = 32'h05c00393;
    memory[57] = 32'hfe72c6e3;
    memory[58] = 32'hfff00e13;
    memory[59] = 32'h04800293;
    memory[60] = 32'h005f8333;
    memory[61] = 32'h01c30023;
    memory[62] = 32'h06800293;
    memory[63] = 32'h005f8333;
    memory[64] = 32'h01c30023;
    memory[65] = 32'h0c000e13;
    memory[66] = 32'h05400293;
    memory[67] = 32'h005f8333;
    memory[68] = 32'h01c30023;
    memory[69] = 32'h06500293;
    memory[70] = 32'h005f8333;
    memory[71] = 32'h01c30023;
    memory[72] = 32'h0035d293;
    memory[73] = 32'h00529293;
    memory[74] = 32'h00a282b3;
    memory[75] = 32'h005f8333;
    memory[76] = 32'h0075f393;
    memory[77] = 32'h00100e13;
    memory[78] = 32'h00038863;
    memory[79] = 32'h001e1e13;
    memory[80] = 32'hfff38393;
    memory[81] = 32'hff5ff06f;
    memory[82] = 32'h01c30023;
    memory[83] = 32'hec9ff06f;
  end

  always @(*) begin
    instruction = memory[word_addr];
  end
endmodule
