// (* keep_hierarchy = "yes" *)
module inst_mem (
    input  wire [31:0] pc_address,
    output reg  [31:0] instruction
);
  localparam NUM_OF_INST = 1024;
  localparam ADDR_W = $clog2(NUM_OF_INST);

  // Force distributed ROM (combinational read)
  (* rom_style = "distributed" *) reg [31:0] memory [0:NUM_OF_INST-1];
  wire [ADDR_W-1:0] word_addr = pc_address[2 + ADDR_W - 1 : 2];

  integer i;
  initial begin
    // default fill with NOP
    for (i = 0; i < NUM_OF_INST; i = i + 1) begin
      memory[i] = 32'h00000013;
    end

    // paste your instructions here (generated by python)
    memory[0] = 32'h00008437;
    memory[1] = 32'h000094b7;
    memory[2] = 32'h0000a937;
    memory[3] = 32'h000019b7;
    memory[4] = 32'h00800293;
    memory[5] = 32'h00502023;
    memory[6] = 32'h00502423;
    memory[7] = 32'h02800293;
    memory[8] = 32'h00502223;
    memory[9] = 32'h00502623;
    memory[10] = 32'h0b0000ef;
    memory[11] = 32'h00002503;
    memory[12] = 32'h00402583;
    memory[13] = 32'h0c8000ef;
    memory[14] = 32'h0004a023;
    memory[15] = 32'h00042283;
    memory[16] = 32'h00802503;
    memory[17] = 32'h00c02583;
    memory[18] = 32'h0b4000ef;
    memory[19] = 32'h00002383;
    memory[20] = 32'h00402e03;
    memory[21] = 32'h0012f313;
    memory[22] = 32'h00030663;
    memory[23] = 32'h000e0463;
    memory[24] = 32'hfffe0e13;
    memory[25] = 32'h0022f313;
    memory[26] = 32'h00030863;
    memory[27] = 32'h03e00e93;
    memory[28] = 32'h01de5463;
    memory[29] = 32'h001e0e13;
    memory[30] = 32'h0042f313;
    memory[31] = 32'h00030663;
    memory[32] = 32'h00038463;
    memory[33] = 32'hfff38393;
    memory[34] = 32'h0082f313;
    memory[35] = 32'h00030863;
    memory[36] = 32'h07e00e93;
    memory[37] = 32'h01d3d463;
    memory[38] = 32'h00138393;
    memory[39] = 32'h00702023;
    memory[40] = 32'h01c02223;
    memory[41] = 32'h00702423;
    memory[42] = 32'h01c02623;
    memory[43] = 32'h00038513;
    memory[44] = 32'h000e0593;
    memory[45] = 32'h048000ef;
    memory[46] = 32'h0004a023;
    memory[47] = 32'h00600f13;
    memory[48] = 32'h7d000f93;
    memory[49] = 32'hffff8f93;
    memory[50] = 32'hfe0f9ee3;
    memory[51] = 32'hffff0f13;
    memory[52] = 32'hfe0f18e3;
    memory[53] = 32'hf69ff06f;
    memory[54] = 32'h00000293;
    memory[55] = 32'h00598333;
    memory[56] = 32'h00034383;
    memory[57] = 32'h00590e33;
    memory[58] = 32'h007e0023;
    memory[59] = 32'h00128293;
    memory[60] = 32'h40000e93;
    memory[61] = 32'hffd2c4e3;
    memory[62] = 32'h00008067;
    memory[63] = 32'h00008d13;
    memory[64] = 32'h028000ef;
    memory[65] = 32'h00150513;
    memory[66] = 32'h020000ef;
    memory[67] = 32'hfff50513;
    memory[68] = 32'h00158593;
    memory[69] = 32'h014000ef;
    memory[70] = 32'h00150513;
    memory[71] = 32'h00c000ef;
    memory[72] = 32'h000d0093;
    memory[73] = 32'h00008067;
    memory[74] = 32'h0035d293;
    memory[75] = 32'h00729293;
    memory[76] = 32'h00a282b3;
    memory[77] = 32'h012282b3;
    memory[78] = 32'h0075f313;
    memory[79] = 32'h00100393;
    memory[80] = 32'h00030863;
    memory[81] = 32'h00139393;
    memory[82] = 32'hfff30313;
    memory[83] = 32'hff5ff06f;
    memory[84] = 32'h0002ce03;
    memory[85] = 32'h007e4e33;
    memory[86] = 32'h01c28023;
    memory[87] = 32'h00008067;
  end

  always @(*) begin
    instruction = memory[word_addr];
  end
endmodule
