// (* keep_hierarchy = "yes" *)
module inst_mem (
    input  wire [31:0] pc_address,
    output reg  [31:0] instruction
);
  localparam NUM_OF_INST = 200;
  localparam ADDR_W = $clog2(NUM_OF_INST);

  // Force distributed ROM (combinational read)
  (* rom_style = "distributed" *) reg [31:0] memory [0:NUM_OF_INST-1];
  wire [ADDR_W-1:0] word_addr = pc_address[2 + ADDR_W - 1 : 2];

  integer i;
  initial begin
    // default fill with NOP
    for (i = 0; i < NUM_OF_INST; i = i + 1) begin
      memory[i] = 32'h00000013;
    end

    // paste your instructions here (generated by python)
    memory[0] = 32'h06400293;
    memory[1] = 32'h00004337;
    memory[2] = 32'h00400393;
    memory[3] = 32'h00532023;
    memory[4] = 32'h00532223;
    memory[5] = 32'h00830313;
    memory[6] = 32'hfff38393;
    memory[7] = 32'hfe0398e3;
    memory[8] = 32'h00000513;
    memory[9] = 32'h00000a93;
    memory[10] = 32'h00008f37;
    memory[11] = 32'h004f2383;
    memory[12] = 32'h41538e33;
    memory[13] = 32'h014e5e13;
    memory[14] = 32'h000e0663;
    memory[15] = 32'h02c000ef;
    memory[16] = 32'h00038a93;
    memory[17] = 32'h000f2a03;
    memory[18] = 32'h001a7e93;
    memory[19] = 32'h040e9a63;
    memory[20] = 32'h002a7e93;
    memory[21] = 32'h060e9a63;
    memory[22] = 32'h004a7e93;
    memory[23] = 32'h0e0e9063;
    memory[24] = 32'h090000ef;
    memory[25] = 32'hfc9ff06f;
    memory[26] = 32'h00351f13;
    memory[27] = 32'h00004fb7;
    memory[28] = 32'h01ff0f33;
    memory[29] = 32'h000f2283;
    memory[30] = 32'hfff28293;
    memory[31] = 32'h0002d463;
    memory[32] = 32'h00000293;
    memory[33] = 32'h005f2023;
    memory[34] = 32'h004f2283;
    memory[35] = 32'hfff28293;
    memory[36] = 32'h0002d463;
    memory[37] = 32'h00000293;
    memory[38] = 32'h005f2223;
    memory[39] = 32'h00008067;
    memory[40] = 32'h00351f13;
    memory[41] = 32'h00004fb7;
    memory[42] = 32'h01ff0f33;
    memory[43] = 32'h000f2283;
    memory[44] = 32'h00a28293;
    memory[45] = 32'h06400313;
    memory[46] = 32'h0062c463;
    memory[47] = 32'h06400293;
    memory[48] = 32'h005f2023;
    memory[49] = 32'hf69ff06f;
    memory[50] = 32'h00351f13;
    memory[51] = 32'h00004fb7;
    memory[52] = 32'h01ff0f33;
    memory[53] = 32'h004f2283;
    memory[54] = 32'h00a28293;
    memory[55] = 32'h06400313;
    memory[56] = 32'h0062c463;
    memory[57] = 32'h06400293;
    memory[58] = 32'h005f2223;
    memory[59] = 32'hf41ff06f;
    memory[60] = 32'h00351f13;
    memory[61] = 32'h00004fb7;
    memory[62] = 32'h01ff0f33;
    memory[63] = 32'h000f2283;
    memory[64] = 32'h01e00313;
    memory[65] = 32'h0062ca63;
    memory[66] = 32'h004f2283;
    memory[67] = 32'h0062ca63;
    memory[68] = 32'h00000513;
    memory[69] = 32'h0140006f;
    memory[70] = 32'h00100513;
    memory[71] = 32'h00c0006f;
    memory[72] = 32'h00200513;
    memory[73] = 32'h0040006f;
    memory[74] = 32'h00009eb7;
    memory[75] = 32'h00851f13;
    memory[76] = 32'h00af6f33;
    memory[77] = 32'h01eea023;
    memory[78] = 32'h00008067;
    memory[79] = 32'h00150513;
    memory[80] = 32'h00400e93;
    memory[81] = 32'h01d54463;
    memory[82] = 32'h00000513;
    memory[83] = 32'hee1ff06f;
  end

  always @(*) begin
    instruction = memory[word_addr];
  end
endmodule
